//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace ABS.Web.Areas.SECONDARYSALESMISREPORT.Reports.MemoWiseRetailerDelivery {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("MemoWiseRetailerDelivery")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class MemoWiseRetailerDelivery : global::System.Data.DataSet {
        
        private DSMemoWiseDeliveryDataTable tableDSMemoWiseDelivery;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public MemoWiseRetailerDelivery() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected MemoWiseRetailerDelivery(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["DSMemoWiseDelivery"] != null)) {
                    base.Tables.Add(new DSMemoWiseDeliveryDataTable(ds.Tables["DSMemoWiseDelivery"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public DSMemoWiseDeliveryDataTable DSMemoWiseDelivery {
            get {
                return this.tableDSMemoWiseDelivery;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            MemoWiseRetailerDelivery cln = ((MemoWiseRetailerDelivery)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["DSMemoWiseDelivery"] != null)) {
                    base.Tables.Add(new DSMemoWiseDeliveryDataTable(ds.Tables["DSMemoWiseDelivery"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableDSMemoWiseDelivery = ((DSMemoWiseDeliveryDataTable)(base.Tables["DSMemoWiseDelivery"]));
            if ((initTable == true)) {
                if ((this.tableDSMemoWiseDelivery != null)) {
                    this.tableDSMemoWiseDelivery.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void InitClass() {
            this.DataSetName = "MemoWiseRetailerDelivery";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/MemoWiseRetailerDelivery.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableDSMemoWiseDelivery = new DSMemoWiseDeliveryDataTable();
            base.Tables.Add(this.tableDSMemoWiseDelivery);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private bool ShouldSerializeDSMemoWiseDelivery() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            MemoWiseRetailerDelivery ds = new MemoWiseRetailerDelivery();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public delegate void DSMemoWiseDeliveryRowChangeEventHandler(object sender, DSMemoWiseDeliveryRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class DSMemoWiseDeliveryDataTable : global::System.Data.TypedTableBase<DSMemoWiseDeliveryRow> {
            
            private global::System.Data.DataColumn columnDIST_ID;
            
            private global::System.Data.DataColumn columnDIST_NAME;
            
            private global::System.Data.DataColumn columnROUTE_ID;
            
            private global::System.Data.DataColumn columnROUTE_NAME;
            
            private global::System.Data.DataColumn columnRETAILER_ID;
            
            private global::System.Data.DataColumn columnRETAILER_NAME;
            
            private global::System.Data.DataColumn columnSALES_ORDER_ID;
            
            private global::System.Data.DataColumn columnDELIVERY_DATE;
            
            private global::System.Data.DataColumn columnBRAND_NAME;
            
            private global::System.Data.DataColumn columnPRODUCT_NAME;
            
            private global::System.Data.DataColumn columnPCS_PER_CTN;
            
            private global::System.Data.DataColumn columnDLV_QTY_CTN;
            
            private global::System.Data.DataColumn columnDLV_QTY_PCS;
            
            private global::System.Data.DataColumn columnTP_PCS;
            
            private global::System.Data.DataColumn columnOFFER_ID;
            
            private global::System.Data.DataColumn columnOFFER_DETAILS;
            
            private global::System.Data.DataColumn columnOFFER_PRODUCT_ID;
            
            private global::System.Data.DataColumn columnOFFER_PRODUCT_NAME;
            
            private global::System.Data.DataColumn columnOFFER_PRODUCT_QNT_PCS;
            
            private global::System.Data.DataColumn columnOFFER_DISCOUNT_AMOUNT;
            
            private global::System.Data.DataColumn columnDIST_DISCOUNT_AMOUNT;
            
            private global::System.Data.DataColumn columnSALES_VALUE;
            
            private global::System.Data.DataColumn columnNET_VALUE;
            
            private global::System.Data.DataColumn columnSPRSN_NAME;
            
            private global::System.Data.DataColumn columnZONE_NAME;
            
            private global::System.Data.DataColumn columnREGION_NAME;
            
            private global::System.Data.DataColumn columnDIVISION_NAME;
            
            private global::System.Data.DataColumn columnRETAILER_ADDR;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DSMemoWiseDeliveryDataTable() {
                this.TableName = "DSMemoWiseDelivery";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal DSMemoWiseDeliveryDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected DSMemoWiseDeliveryDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DIST_IDColumn {
                get {
                    return this.columnDIST_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DIST_NAMEColumn {
                get {
                    return this.columnDIST_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ROUTE_IDColumn {
                get {
                    return this.columnROUTE_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ROUTE_NAMEColumn {
                get {
                    return this.columnROUTE_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn RETAILER_IDColumn {
                get {
                    return this.columnRETAILER_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn RETAILER_NAMEColumn {
                get {
                    return this.columnRETAILER_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn SALES_ORDER_IDColumn {
                get {
                    return this.columnSALES_ORDER_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DELIVERY_DATEColumn {
                get {
                    return this.columnDELIVERY_DATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn BRAND_NAMEColumn {
                get {
                    return this.columnBRAND_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn PRODUCT_NAMEColumn {
                get {
                    return this.columnPRODUCT_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn PCS_PER_CTNColumn {
                get {
                    return this.columnPCS_PER_CTN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DLV_QTY_CTNColumn {
                get {
                    return this.columnDLV_QTY_CTN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DLV_QTY_PCSColumn {
                get {
                    return this.columnDLV_QTY_PCS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn TP_PCSColumn {
                get {
                    return this.columnTP_PCS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn OFFER_IDColumn {
                get {
                    return this.columnOFFER_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn OFFER_DETAILSColumn {
                get {
                    return this.columnOFFER_DETAILS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn OFFER_PRODUCT_IDColumn {
                get {
                    return this.columnOFFER_PRODUCT_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn OFFER_PRODUCT_NAMEColumn {
                get {
                    return this.columnOFFER_PRODUCT_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn OFFER_PRODUCT_QNT_PCSColumn {
                get {
                    return this.columnOFFER_PRODUCT_QNT_PCS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn OFFER_DISCOUNT_AMOUNTColumn {
                get {
                    return this.columnOFFER_DISCOUNT_AMOUNT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DIST_DISCOUNT_AMOUNTColumn {
                get {
                    return this.columnDIST_DISCOUNT_AMOUNT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn SALES_VALUEColumn {
                get {
                    return this.columnSALES_VALUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn NET_VALUEColumn {
                get {
                    return this.columnNET_VALUE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn SPRSN_NAMEColumn {
                get {
                    return this.columnSPRSN_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn ZONE_NAMEColumn {
                get {
                    return this.columnZONE_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn REGION_NAMEColumn {
                get {
                    return this.columnREGION_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn DIVISION_NAMEColumn {
                get {
                    return this.columnDIVISION_NAME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataColumn RETAILER_ADDRColumn {
                get {
                    return this.columnRETAILER_ADDR;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DSMemoWiseDeliveryRow this[int index] {
                get {
                    return ((DSMemoWiseDeliveryRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event DSMemoWiseDeliveryRowChangeEventHandler DSMemoWiseDeliveryRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event DSMemoWiseDeliveryRowChangeEventHandler DSMemoWiseDeliveryRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event DSMemoWiseDeliveryRowChangeEventHandler DSMemoWiseDeliveryRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public event DSMemoWiseDeliveryRowChangeEventHandler DSMemoWiseDeliveryRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void AddDSMemoWiseDeliveryRow(DSMemoWiseDeliveryRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DSMemoWiseDeliveryRow AddDSMemoWiseDeliveryRow(
                        string DIST_ID, 
                        string DIST_NAME, 
                        string ROUTE_ID, 
                        string ROUTE_NAME, 
                        string RETAILER_ID, 
                        string RETAILER_NAME, 
                        string SALES_ORDER_ID, 
                        string DELIVERY_DATE, 
                        string BRAND_NAME, 
                        string PRODUCT_NAME, 
                        string PCS_PER_CTN, 
                        string DLV_QTY_CTN, 
                        string DLV_QTY_PCS, 
                        string TP_PCS, 
                        string OFFER_ID, 
                        string OFFER_DETAILS, 
                        string OFFER_PRODUCT_ID, 
                        string OFFER_PRODUCT_NAME, 
                        string OFFER_PRODUCT_QNT_PCS, 
                        string OFFER_DISCOUNT_AMOUNT, 
                        string DIST_DISCOUNT_AMOUNT, 
                        string SALES_VALUE, 
                        string NET_VALUE, 
                        string SPRSN_NAME, 
                        string ZONE_NAME, 
                        string REGION_NAME, 
                        string DIVISION_NAME, 
                        string RETAILER_ADDR) {
                DSMemoWiseDeliveryRow rowDSMemoWiseDeliveryRow = ((DSMemoWiseDeliveryRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        DIST_ID,
                        DIST_NAME,
                        ROUTE_ID,
                        ROUTE_NAME,
                        RETAILER_ID,
                        RETAILER_NAME,
                        SALES_ORDER_ID,
                        DELIVERY_DATE,
                        BRAND_NAME,
                        PRODUCT_NAME,
                        PCS_PER_CTN,
                        DLV_QTY_CTN,
                        DLV_QTY_PCS,
                        TP_PCS,
                        OFFER_ID,
                        OFFER_DETAILS,
                        OFFER_PRODUCT_ID,
                        OFFER_PRODUCT_NAME,
                        OFFER_PRODUCT_QNT_PCS,
                        OFFER_DISCOUNT_AMOUNT,
                        DIST_DISCOUNT_AMOUNT,
                        SALES_VALUE,
                        NET_VALUE,
                        SPRSN_NAME,
                        ZONE_NAME,
                        REGION_NAME,
                        DIVISION_NAME,
                        RETAILER_ADDR};
                rowDSMemoWiseDeliveryRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowDSMemoWiseDeliveryRow);
                return rowDSMemoWiseDeliveryRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                DSMemoWiseDeliveryDataTable cln = ((DSMemoWiseDeliveryDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new DSMemoWiseDeliveryDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal void InitVars() {
                this.columnDIST_ID = base.Columns["DIST_ID"];
                this.columnDIST_NAME = base.Columns["DIST_NAME"];
                this.columnROUTE_ID = base.Columns["ROUTE_ID"];
                this.columnROUTE_NAME = base.Columns["ROUTE_NAME"];
                this.columnRETAILER_ID = base.Columns["RETAILER_ID"];
                this.columnRETAILER_NAME = base.Columns["RETAILER_NAME"];
                this.columnSALES_ORDER_ID = base.Columns["SALES_ORDER_ID"];
                this.columnDELIVERY_DATE = base.Columns["DELIVERY_DATE"];
                this.columnBRAND_NAME = base.Columns["BRAND_NAME"];
                this.columnPRODUCT_NAME = base.Columns["PRODUCT_NAME"];
                this.columnPCS_PER_CTN = base.Columns["PCS_PER_CTN"];
                this.columnDLV_QTY_CTN = base.Columns["DLV_QTY_CTN"];
                this.columnDLV_QTY_PCS = base.Columns["DLV_QTY_PCS"];
                this.columnTP_PCS = base.Columns["TP_PCS"];
                this.columnOFFER_ID = base.Columns["OFFER_ID"];
                this.columnOFFER_DETAILS = base.Columns["OFFER_DETAILS"];
                this.columnOFFER_PRODUCT_ID = base.Columns["OFFER_PRODUCT_ID"];
                this.columnOFFER_PRODUCT_NAME = base.Columns["OFFER_PRODUCT_NAME"];
                this.columnOFFER_PRODUCT_QNT_PCS = base.Columns["OFFER_PRODUCT_QNT_PCS"];
                this.columnOFFER_DISCOUNT_AMOUNT = base.Columns["OFFER_DISCOUNT_AMOUNT"];
                this.columnDIST_DISCOUNT_AMOUNT = base.Columns["DIST_DISCOUNT_AMOUNT"];
                this.columnSALES_VALUE = base.Columns["SALES_VALUE"];
                this.columnNET_VALUE = base.Columns["NET_VALUE"];
                this.columnSPRSN_NAME = base.Columns["SPRSN_NAME"];
                this.columnZONE_NAME = base.Columns["ZONE_NAME"];
                this.columnREGION_NAME = base.Columns["REGION_NAME"];
                this.columnDIVISION_NAME = base.Columns["DIVISION_NAME"];
                this.columnRETAILER_ADDR = base.Columns["RETAILER_ADDR"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            private void InitClass() {
                this.columnDIST_ID = new global::System.Data.DataColumn("DIST_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDIST_ID);
                this.columnDIST_NAME = new global::System.Data.DataColumn("DIST_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDIST_NAME);
                this.columnROUTE_ID = new global::System.Data.DataColumn("ROUTE_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnROUTE_ID);
                this.columnROUTE_NAME = new global::System.Data.DataColumn("ROUTE_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnROUTE_NAME);
                this.columnRETAILER_ID = new global::System.Data.DataColumn("RETAILER_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRETAILER_ID);
                this.columnRETAILER_NAME = new global::System.Data.DataColumn("RETAILER_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRETAILER_NAME);
                this.columnSALES_ORDER_ID = new global::System.Data.DataColumn("SALES_ORDER_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSALES_ORDER_ID);
                this.columnDELIVERY_DATE = new global::System.Data.DataColumn("DELIVERY_DATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDELIVERY_DATE);
                this.columnBRAND_NAME = new global::System.Data.DataColumn("BRAND_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBRAND_NAME);
                this.columnPRODUCT_NAME = new global::System.Data.DataColumn("PRODUCT_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPRODUCT_NAME);
                this.columnPCS_PER_CTN = new global::System.Data.DataColumn("PCS_PER_CTN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPCS_PER_CTN);
                this.columnDLV_QTY_CTN = new global::System.Data.DataColumn("DLV_QTY_CTN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDLV_QTY_CTN);
                this.columnDLV_QTY_PCS = new global::System.Data.DataColumn("DLV_QTY_PCS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDLV_QTY_PCS);
                this.columnTP_PCS = new global::System.Data.DataColumn("TP_PCS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTP_PCS);
                this.columnOFFER_ID = new global::System.Data.DataColumn("OFFER_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOFFER_ID);
                this.columnOFFER_DETAILS = new global::System.Data.DataColumn("OFFER_DETAILS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOFFER_DETAILS);
                this.columnOFFER_PRODUCT_ID = new global::System.Data.DataColumn("OFFER_PRODUCT_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOFFER_PRODUCT_ID);
                this.columnOFFER_PRODUCT_NAME = new global::System.Data.DataColumn("OFFER_PRODUCT_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOFFER_PRODUCT_NAME);
                this.columnOFFER_PRODUCT_QNT_PCS = new global::System.Data.DataColumn("OFFER_PRODUCT_QNT_PCS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOFFER_PRODUCT_QNT_PCS);
                this.columnOFFER_DISCOUNT_AMOUNT = new global::System.Data.DataColumn("OFFER_DISCOUNT_AMOUNT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOFFER_DISCOUNT_AMOUNT);
                this.columnDIST_DISCOUNT_AMOUNT = new global::System.Data.DataColumn("DIST_DISCOUNT_AMOUNT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDIST_DISCOUNT_AMOUNT);
                this.columnSALES_VALUE = new global::System.Data.DataColumn("SALES_VALUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSALES_VALUE);
                this.columnNET_VALUE = new global::System.Data.DataColumn("NET_VALUE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNET_VALUE);
                this.columnSPRSN_NAME = new global::System.Data.DataColumn("SPRSN_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSPRSN_NAME);
                this.columnZONE_NAME = new global::System.Data.DataColumn("ZONE_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnZONE_NAME);
                this.columnREGION_NAME = new global::System.Data.DataColumn("REGION_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREGION_NAME);
                this.columnDIVISION_NAME = new global::System.Data.DataColumn("DIVISION_NAME", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDIVISION_NAME);
                this.columnRETAILER_ADDR = new global::System.Data.DataColumn("RETAILER_ADDR", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRETAILER_ADDR);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DSMemoWiseDeliveryRow NewDSMemoWiseDeliveryRow() {
                return ((DSMemoWiseDeliveryRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new DSMemoWiseDeliveryRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(DSMemoWiseDeliveryRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.DSMemoWiseDeliveryRowChanged != null)) {
                    this.DSMemoWiseDeliveryRowChanged(this, new DSMemoWiseDeliveryRowChangeEvent(((DSMemoWiseDeliveryRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.DSMemoWiseDeliveryRowChanging != null)) {
                    this.DSMemoWiseDeliveryRowChanging(this, new DSMemoWiseDeliveryRowChangeEvent(((DSMemoWiseDeliveryRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.DSMemoWiseDeliveryRowDeleted != null)) {
                    this.DSMemoWiseDeliveryRowDeleted(this, new DSMemoWiseDeliveryRowChangeEvent(((DSMemoWiseDeliveryRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.DSMemoWiseDeliveryRowDeleting != null)) {
                    this.DSMemoWiseDeliveryRowDeleting(this, new DSMemoWiseDeliveryRowChangeEvent(((DSMemoWiseDeliveryRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void RemoveDSMemoWiseDeliveryRow(DSMemoWiseDeliveryRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                MemoWiseRetailerDelivery ds = new MemoWiseRetailerDelivery();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "DSMemoWiseDeliveryDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class DSMemoWiseDeliveryRow : global::System.Data.DataRow {
            
            private DSMemoWiseDeliveryDataTable tableDSMemoWiseDelivery;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            internal DSMemoWiseDeliveryRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableDSMemoWiseDelivery = ((DSMemoWiseDeliveryDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string DIST_ID {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.DIST_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DIST_ID\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.DIST_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string DIST_NAME {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.DIST_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DIST_NAME\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.DIST_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ROUTE_ID {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.ROUTE_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ROUTE_ID\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.ROUTE_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ROUTE_NAME {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.ROUTE_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ROUTE_NAME\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.ROUTE_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string RETAILER_ID {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.RETAILER_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RETAILER_ID\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.RETAILER_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string RETAILER_NAME {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.RETAILER_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RETAILER_NAME\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.RETAILER_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string SALES_ORDER_ID {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.SALES_ORDER_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SALES_ORDER_ID\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.SALES_ORDER_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string DELIVERY_DATE {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.DELIVERY_DATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DELIVERY_DATE\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.DELIVERY_DATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string BRAND_NAME {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.BRAND_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BRAND_NAME\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.BRAND_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string PRODUCT_NAME {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.PRODUCT_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PRODUCT_NAME\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.PRODUCT_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string PCS_PER_CTN {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.PCS_PER_CTNColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PCS_PER_CTN\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.PCS_PER_CTNColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string DLV_QTY_CTN {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.DLV_QTY_CTNColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DLV_QTY_CTN\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.DLV_QTY_CTNColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string DLV_QTY_PCS {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.DLV_QTY_PCSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DLV_QTY_PCS\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.DLV_QTY_PCSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string TP_PCS {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.TP_PCSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TP_PCS\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.TP_PCSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string OFFER_ID {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.OFFER_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OFFER_ID\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.OFFER_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string OFFER_DETAILS {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.OFFER_DETAILSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OFFER_DETAILS\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.OFFER_DETAILSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string OFFER_PRODUCT_ID {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.OFFER_PRODUCT_IDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OFFER_PRODUCT_ID\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.OFFER_PRODUCT_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string OFFER_PRODUCT_NAME {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.OFFER_PRODUCT_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OFFER_PRODUCT_NAME\' in table \'DSMemoWiseDelivery\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.OFFER_PRODUCT_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string OFFER_PRODUCT_QNT_PCS {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.OFFER_PRODUCT_QNT_PCSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OFFER_PRODUCT_QNT_PCS\' in table \'DSMemoWiseDelivery\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.OFFER_PRODUCT_QNT_PCSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string OFFER_DISCOUNT_AMOUNT {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.OFFER_DISCOUNT_AMOUNTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OFFER_DISCOUNT_AMOUNT\' in table \'DSMemoWiseDelivery\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.OFFER_DISCOUNT_AMOUNTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string DIST_DISCOUNT_AMOUNT {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.DIST_DISCOUNT_AMOUNTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DIST_DISCOUNT_AMOUNT\' in table \'DSMemoWiseDelivery\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.DIST_DISCOUNT_AMOUNTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string SALES_VALUE {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.SALES_VALUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SALES_VALUE\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.SALES_VALUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string NET_VALUE {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.NET_VALUEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NET_VALUE\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.NET_VALUEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string SPRSN_NAME {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.SPRSN_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SPRSN_NAME\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.SPRSN_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string ZONE_NAME {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.ZONE_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ZONE_NAME\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.ZONE_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string REGION_NAME {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.REGION_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'REGION_NAME\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.REGION_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string DIVISION_NAME {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.DIVISION_NAMEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DIVISION_NAME\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.DIVISION_NAMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public string RETAILER_ADDR {
                get {
                    try {
                        return ((string)(this[this.tableDSMemoWiseDelivery.RETAILER_ADDRColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RETAILER_ADDR\' in table \'DSMemoWiseDelivery\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDSMemoWiseDelivery.RETAILER_ADDRColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDIST_IDNull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.DIST_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDIST_IDNull() {
                this[this.tableDSMemoWiseDelivery.DIST_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDIST_NAMENull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.DIST_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDIST_NAMENull() {
                this[this.tableDSMemoWiseDelivery.DIST_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsROUTE_IDNull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.ROUTE_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetROUTE_IDNull() {
                this[this.tableDSMemoWiseDelivery.ROUTE_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsROUTE_NAMENull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.ROUTE_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetROUTE_NAMENull() {
                this[this.tableDSMemoWiseDelivery.ROUTE_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsRETAILER_IDNull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.RETAILER_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetRETAILER_IDNull() {
                this[this.tableDSMemoWiseDelivery.RETAILER_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsRETAILER_NAMENull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.RETAILER_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetRETAILER_NAMENull() {
                this[this.tableDSMemoWiseDelivery.RETAILER_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSALES_ORDER_IDNull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.SALES_ORDER_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSALES_ORDER_IDNull() {
                this[this.tableDSMemoWiseDelivery.SALES_ORDER_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDELIVERY_DATENull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.DELIVERY_DATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDELIVERY_DATENull() {
                this[this.tableDSMemoWiseDelivery.DELIVERY_DATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsBRAND_NAMENull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.BRAND_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetBRAND_NAMENull() {
                this[this.tableDSMemoWiseDelivery.BRAND_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsPRODUCT_NAMENull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.PRODUCT_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetPRODUCT_NAMENull() {
                this[this.tableDSMemoWiseDelivery.PRODUCT_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsPCS_PER_CTNNull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.PCS_PER_CTNColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetPCS_PER_CTNNull() {
                this[this.tableDSMemoWiseDelivery.PCS_PER_CTNColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDLV_QTY_CTNNull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.DLV_QTY_CTNColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDLV_QTY_CTNNull() {
                this[this.tableDSMemoWiseDelivery.DLV_QTY_CTNColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDLV_QTY_PCSNull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.DLV_QTY_PCSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDLV_QTY_PCSNull() {
                this[this.tableDSMemoWiseDelivery.DLV_QTY_PCSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsTP_PCSNull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.TP_PCSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetTP_PCSNull() {
                this[this.tableDSMemoWiseDelivery.TP_PCSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsOFFER_IDNull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.OFFER_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetOFFER_IDNull() {
                this[this.tableDSMemoWiseDelivery.OFFER_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsOFFER_DETAILSNull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.OFFER_DETAILSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetOFFER_DETAILSNull() {
                this[this.tableDSMemoWiseDelivery.OFFER_DETAILSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsOFFER_PRODUCT_IDNull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.OFFER_PRODUCT_IDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetOFFER_PRODUCT_IDNull() {
                this[this.tableDSMemoWiseDelivery.OFFER_PRODUCT_IDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsOFFER_PRODUCT_NAMENull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.OFFER_PRODUCT_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetOFFER_PRODUCT_NAMENull() {
                this[this.tableDSMemoWiseDelivery.OFFER_PRODUCT_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsOFFER_PRODUCT_QNT_PCSNull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.OFFER_PRODUCT_QNT_PCSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetOFFER_PRODUCT_QNT_PCSNull() {
                this[this.tableDSMemoWiseDelivery.OFFER_PRODUCT_QNT_PCSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsOFFER_DISCOUNT_AMOUNTNull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.OFFER_DISCOUNT_AMOUNTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetOFFER_DISCOUNT_AMOUNTNull() {
                this[this.tableDSMemoWiseDelivery.OFFER_DISCOUNT_AMOUNTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDIST_DISCOUNT_AMOUNTNull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.DIST_DISCOUNT_AMOUNTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDIST_DISCOUNT_AMOUNTNull() {
                this[this.tableDSMemoWiseDelivery.DIST_DISCOUNT_AMOUNTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSALES_VALUENull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.SALES_VALUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSALES_VALUENull() {
                this[this.tableDSMemoWiseDelivery.SALES_VALUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsNET_VALUENull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.NET_VALUEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetNET_VALUENull() {
                this[this.tableDSMemoWiseDelivery.NET_VALUEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsSPRSN_NAMENull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.SPRSN_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetSPRSN_NAMENull() {
                this[this.tableDSMemoWiseDelivery.SPRSN_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsZONE_NAMENull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.ZONE_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetZONE_NAMENull() {
                this[this.tableDSMemoWiseDelivery.ZONE_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsREGION_NAMENull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.REGION_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetREGION_NAMENull() {
                this[this.tableDSMemoWiseDelivery.REGION_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsDIVISION_NAMENull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.DIVISION_NAMEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetDIVISION_NAMENull() {
                this[this.tableDSMemoWiseDelivery.DIVISION_NAMEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public bool IsRETAILER_ADDRNull() {
                return this.IsNull(this.tableDSMemoWiseDelivery.RETAILER_ADDRColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public void SetRETAILER_ADDRNull() {
                this[this.tableDSMemoWiseDelivery.RETAILER_ADDRColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
        public class DSMemoWiseDeliveryRowChangeEvent : global::System.EventArgs {
            
            private DSMemoWiseDeliveryRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DSMemoWiseDeliveryRowChangeEvent(DSMemoWiseDeliveryRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public DSMemoWiseDeliveryRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "15.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591