//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTGroup.OracleModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CMNCOMPANY
    {
        public int COMPANYID { get; set; }
        public string CUSTOMCODE { get; set; }
        public string COMPANYSHORTNAME { get; set; }
        public string COMPANYNAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public Nullable<int> CITYID { get; set; }
        public Nullable<int> COUNTRYID { get; set; }
        public Nullable<int> STAETID { get; set; }
        public Nullable<int> CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATEON { get; set; }
        public string CREATEPC { get; set; }
        public Nullable<int> UPDATEBY { get; set; }
        public Nullable<System.DateTime> UPDATEON { get; set; }
        public string UPDATEPC { get; set; }
        public bool ISDELETED { get; set; }
        public Nullable<int> DELETEBY { get; set; }
        public Nullable<System.DateTime> DELETEON { get; set; }
        public string DELETEPC { get; set; }
        public string LOGO { get; set; }
    }
}
