//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTGroup.OracleModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_INCEN_RATE_DIST_RATIO
    {
        public decimal ID { get; set; }
        public decimal RATE_ID { get; set; }
        public string SF_TYPE { get; set; }
        public Nullable<decimal> TK_AMOUNT { get; set; }
        public System.DateTime CREATED_ON { get; set; }
    }
}
